version: '3'

volumes:
  www-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${CONTAINERVOLUMES}/html
  mariadb-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${CONTAINERVOLUMES}/mariadb
  redis-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${CONTAINERVOLUMES}/redis
  backup-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${CONTAINERVOLUMES}/backup

services:
#  sshd:
#    image: hermsi/alpine-sshd
#    container_name: ${COMPOSE_PROJECT_NAME}-SSH
#    environment:
#      ROOT_PASSWORD: ${ROOT_PASSWORD}
#    ports:
#      - "${SSH_PORT}:22"
#    volumes:
#      - www-data:/var/www/html

  apache:
    image: thecodingmachine/php:7.4-v4-apache
    container_name: ${COMPOSE_PROJECT_NAME}-Apache-PHP
    environment:
      TZ: ${TIMEZONE}
      APACHE_RUN_USER: docker
      APACHE_RUN_GROUP: docker
      PHP_EXTENSION_BCMATH: 1
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_GMP: 1
      PHP_EXTENSION_IMAGICK: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_MYSQLI: 1
      PHP_INI_DISPLAY_ERRORS: 0
      PHP_INI_DATE_TIMEZONE: ${TIMEZONE}
      PHP_INI_MAX_EXECUTION_TIME: 360
      PHP_INI_MEMORY_LIMIT: 756M
      PHP_INI_UPLOAD_MAX_FILESIZE: 64M
      PHP_INI_POST_MAX_SIZE: 64M
      APACHE_DOCUMENT_ROOT: /var/www/html/${COMPOSE_PROJECT_NAME}-Projekt
      CRON_USER_1: docker
      CRON_SCHEDULE_1: 0,5,10,15,20,25,30,35,40,45,50 * * * *
      CRON_COMMAND_1: php /var/www/html/${COMPOSE_PROJECT_NAME}-Projekt/console core:archive
      CRON_USER_2: root
      CRON_SCHEDULE_2: 0 3 * * *
      CRON_COMMAND_2: /backup/HTML-Backup.sh
    volumes:
      - www-data:/var/www/html
      - backup-data:/backup
    networks:
      - default
      - proxy

    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=${HOSTRULE}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=myresolver
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}_SVC
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}_Header
      - traefik.http.services.${COMPOSE_PROJECT_NAME}_SVC.loadBalancer.server.port=80
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_Header.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_Header.headers.customrequestheaders.X-Forwarded-Ssl=on
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_Header.headers.customrequestheaders.X-Forwarded-Port=443
      - traefik.docker.network=traefik_proxy

  mysql:
    image: mariadb:10.5
    container_name: ${COMPOSE_PROJECT_NAME}-MariaDB
    # command für mysql 8.x
    # command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # command für mariadb
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./configs/mariadb:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      TZ: ${TIMEZONE}

  DBBackup:
    image: fradelg/mysql-cron-backup
    container_name: ${COMPOSE_PROJECT_NAME}-DBBackup
    depends_on:
      - mysql
    volumes:
      - backup-data:/backup
    environment:
      TZ: ${TIMEZONE}
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASS: ${MARIADB_ROOT_PASSWORD}
      MAX_BACKUPS: 15
      INIT_BACKUP: 0
      # Every day at 03:00
      CRON_TIME: 0 3 * * *
      # Make it small
      GZIP_LEVEL: 9
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-Redis
    volumes:
      - redis-data:/data

networks:
  proxy:
    external:
      name: ${PROXY_NETWORK}
